pipeline {
    agent any

    stages {
        stage('Code Checkout') {
            steps {
                echo 'Checking out code...'
                // get repo
                git 'https://github.com/repo.git'
            }
        }
        stage('Quality Assurance') {
            steps {
                echo 'Running static analysis...'
                // code quality checks
                sh 'sonar-scanner' 
            }
        }
        stage('Unit Testing') {
            steps {
                echo 'Executing unit tests...'
                // unit testing steps
                sh './gradlew test' 
            }
        }
        stage('Build and Package') {
            steps {
                echo 'Building application...'
                // build and packaging steps
                sh './gradlew assemble' 
            }
        }
        stage('Deployment') {
            steps {
                echo 'Deploying to production...'
                // deployment steps
                sh 'ansible-playbook -i inventory/prod deployment.yml' 
            }
        }
    }

    post {
        always {
            echo 'Sending notifications...'
            // post-build actions (eg notifications)
            mail(to: 'devops@domain.com', subject: 'Build Notification', body: 'The build was successful.')
        }
        failure {
            // Actions to take if the build fails
            mail(to: 'devops@domain.com', subject: 'Build Failed', body: 'The build failed. Please check Jenkins for details.')
        }
    }
}